import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, spacing, typography, borderRadius } from '../src/shared/theme';

const sections = [
  {
    title: 'End User License Agreement',
    body:
      'This app is intended to support anemia screening workflows and education. It does not replace clinical judgment, laboratory testing, or emergency care. You agree to use the app only for lawful health-support purposes and to verify important decisions with a qualified healthcare professional.',
  },
  {
    title: 'Privacy Summary',
    body:
      'The app may process conjunctiva images, age, gender, and optional health details you enter. When signed in, uploaded images and screening history can be stored in Supabase so they are available across sessions. Keep devices protected and avoid uploading images without patient or caregiver consent.',
  },
  {
    title: 'Clinical Safety',
    body:
      'Predictions are assistive outputs generated by machine learning models. False positives and false negatives are possible. Severe symptoms, clinical concern, or worsening condition should always be referred for urgent medical assessment regardless of the app result.',
  },
  {
    title: 'Data Responsibility',
    body:
      'Use only the minimum patient information required for screening. Follow your local privacy, consent, and record-keeping requirements. If you are demonstrating the app, use non-identifiable sample data whenever possible.',
  },
];

export default function LegalScreen() {
  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      <Text style={styles.title}>EULA & Privacy Policy</Text>
      <Text style={styles.subtitle}>
        This summary is provided for Expo development and app testing. Replace it
        with your final reviewed legal text before public release.
      </Text>

      {sections.map((section) => (
        <View key={section.title} style={styles.card}>
          <Text style={styles.cardTitle}>{section.title}</Text>
          <Text style={styles.cardBody}>{section.body}</Text>
        </View>
      ))}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: spacing.lg,
    gap: spacing.md,
  },
  title: {
    ...typography.title,
    color: colors.text,
  },
  subtitle: {
    ...typography.body,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardTitle: {
    ...typography.bodyBold,
    color: colors.primaryDark,
    marginBottom: spacing.sm,
  },
  cardBody: {
    ...typography.body,
    color: colors.text,
    lineHeight: 22,
  },
});
